# Site settings
title: 조혜진
email: jo0920hyejin@gmail.com
url: https://J0Hyejin.github.io
description: "설명란 테스트 메세지"
keywords: "키워드, 테스트, 메세지"
skills: "**#집중력** **#끈기**"
meta_author: Hyejin Jo

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: hyejin

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Other Socials
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  #- title: twitter
  #  url: http://twitter.com/jekyllrb
  #- title: facebook
  #  url:
  #- title: stack-overflow
  #  url: http://stackoverflow.com/questions/tagged/jekyll
  #- title: bitbucket
  #  url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/J0Hyejin/J0Hyejin.github.io
  - title: tistory
    url: https://7i7h.tistory.com/

# Postal address (add as many lines as necessary)
address:
  - line: 부산광역시
#  - line: Beverly Hills, CA 90210

# Credits content
credits: '<a href="http://startbootstrap.com">Freelancer</a> 테마를 이용하여<bar> 만들었습니다.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
